name: Deploy via FTP

on:
  push:
    branches:
      - main 

jobs:
  ftp-deploy:
    name: Deploy para Hostinger via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Baixando o código
        uses: actions/checkout@v3

      - name: Enviando arquivos para o servidor
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}
          local-dir: ./  
